// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YouMai.User.proto

package YouMai.User;

public final class YouMaiUser {
  private YouMaiUser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface User_LoginOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 user_id = 1;
    boolean hasUserId();
    int getUserId();
    
    // optional string device_id = 2;
    boolean hasDeviceId();
    String getDeviceId();
    
    // optional string phone = 3;
    boolean hasPhone();
    String getPhone();
    
    // optional string pwd = 4;
    boolean hasPwd();
    String getPwd();
    
    // optional .YouMai.Basic.Device_Type device_type = 5;
    boolean hasDeviceType();
    YouMai.Basic.YouMaiBasic.Device_Type getDeviceType();
    
    // optional string session_id = 6;
    boolean hasSessionId();
    String getSessionId();
  }
  public static final class User_Login extends
      com.google.protobuf.GeneratedMessage
      implements User_LoginOrBuilder {
    // Use User_Login.newBuilder() to construct.
    private User_Login(Builder builder) {
      super(builder);
    }
    private User_Login(boolean noInit) {}
    
    private static final User_Login defaultInstance;
    public static User_Login getDefaultInstance() {
      return defaultInstance;
    }
    
    public User_Login getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YouMai.User.YouMaiUser.internal_static_YouMai_User_User_Login_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YouMai.User.YouMaiUser.internal_static_YouMai_User_User_Login_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 user_id = 1;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getUserId() {
      return userId_;
    }
    
    // optional string device_id = 2;
    public static final int DEVICE_ID_FIELD_NUMBER = 2;
    private java.lang.Object deviceId_;
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          deviceId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string phone = 3;
    public static final int PHONE_FIELD_NUMBER = 3;
    private java.lang.Object phone_;
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPhone() {
      java.lang.Object ref = phone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          phone_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPhoneBytes() {
      java.lang.Object ref = phone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        phone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string pwd = 4;
    public static final int PWD_FIELD_NUMBER = 4;
    private java.lang.Object pwd_;
    public boolean hasPwd() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getPwd() {
      java.lang.Object ref = pwd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pwd_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPwdBytes() {
      java.lang.Object ref = pwd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .YouMai.Basic.Device_Type device_type = 5;
    public static final int DEVICE_TYPE_FIELD_NUMBER = 5;
    private YouMai.Basic.YouMaiBasic.Device_Type deviceType_;
    public boolean hasDeviceType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public YouMai.Basic.YouMaiBasic.Device_Type getDeviceType() {
      return deviceType_;
    }
    
    // optional string session_id = 6;
    public static final int SESSION_ID_FIELD_NUMBER = 6;
    private java.lang.Object sessionId_;
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sessionId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      userId_ = 0;
      deviceId_ = "";
      phone_ = "";
      pwd_ = "";
      deviceType_ = YouMai.Basic.YouMaiBasic.Device_Type.DeviceType_IPhone;
      sessionId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPhoneBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPwdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, deviceType_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getSessionIdBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPhoneBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPwdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, deviceType_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getSessionIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static YouMai.User.YouMaiUser.User_Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static YouMai.User.YouMaiUser.User_Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.User.YouMaiUser.User_Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static YouMai.User.YouMaiUser.User_Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.User.YouMaiUser.User_Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static YouMai.User.YouMaiUser.User_Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.User.YouMaiUser.User_Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static YouMai.User.YouMaiUser.User_Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static YouMai.User.YouMaiUser.User_Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static YouMai.User.YouMaiUser.User_Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(YouMai.User.YouMaiUser.User_Login prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements YouMai.User.YouMaiUser.User_LoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return YouMai.User.YouMaiUser.internal_static_YouMai_User_User_Login_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return YouMai.User.YouMaiUser.internal_static_YouMai_User_User_Login_fieldAccessorTable;
      }
      
      // Construct using YouMai.User.YouMaiUser.User_Login.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        phone_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        pwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceType_ = YouMai.Basic.YouMaiBasic.Device_Type.DeviceType_IPhone;
        bitField0_ = (bitField0_ & ~0x00000010);
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return YouMai.User.YouMaiUser.User_Login.getDescriptor();
      }
      
      public YouMai.User.YouMaiUser.User_Login getDefaultInstanceForType() {
        return YouMai.User.YouMaiUser.User_Login.getDefaultInstance();
      }
      
      public YouMai.User.YouMaiUser.User_Login build() {
        YouMai.User.YouMaiUser.User_Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private YouMai.User.YouMaiUser.User_Login buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        YouMai.User.YouMaiUser.User_Login result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public YouMai.User.YouMaiUser.User_Login buildPartial() {
        YouMai.User.YouMaiUser.User_Login result = new YouMai.User.YouMaiUser.User_Login(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.phone_ = phone_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pwd_ = pwd_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.deviceType_ = deviceType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sessionId_ = sessionId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof YouMai.User.YouMaiUser.User_Login) {
          return mergeFrom((YouMai.User.YouMaiUser.User_Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(YouMai.User.YouMaiUser.User_Login other) {
        if (other == YouMai.User.YouMaiUser.User_Login.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        if (other.hasPhone()) {
          setPhone(other.getPhone());
        }
        if (other.hasPwd()) {
          setPwd(other.getPwd());
        }
        if (other.hasDeviceType()) {
          setDeviceType(other.getDeviceType());
        }
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              deviceId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              phone_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              pwd_ = input.readBytes();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              YouMai.Basic.YouMaiBasic.Device_Type value = YouMai.Basic.YouMaiBasic.Device_Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                deviceType_ = value;
              }
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              sessionId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 user_id = 1;
      private int userId_ ;
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getUserId() {
        return userId_;
      }
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string device_id = 2;
      private java.lang.Object deviceId_ = "";
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDeviceId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceId_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      void setDeviceId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        deviceId_ = value;
        onChanged();
      }
      
      // optional string phone = 3;
      private java.lang.Object phone_ = "";
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPhone() {
        java.lang.Object ref = phone_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          phone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPhone(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        phone_ = value;
        onChanged();
        return this;
      }
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00000004);
        phone_ = getDefaultInstance().getPhone();
        onChanged();
        return this;
      }
      void setPhone(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        phone_ = value;
        onChanged();
      }
      
      // optional string pwd = 4;
      private java.lang.Object pwd_ = "";
      public boolean hasPwd() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getPwd() {
        java.lang.Object ref = pwd_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pwd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPwd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        pwd_ = value;
        onChanged();
        return this;
      }
      public Builder clearPwd() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pwd_ = getDefaultInstance().getPwd();
        onChanged();
        return this;
      }
      void setPwd(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        pwd_ = value;
        onChanged();
      }
      
      // optional .YouMai.Basic.Device_Type device_type = 5;
      private YouMai.Basic.YouMaiBasic.Device_Type deviceType_ = YouMai.Basic.YouMaiBasic.Device_Type.DeviceType_IPhone;
      public boolean hasDeviceType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public YouMai.Basic.YouMaiBasic.Device_Type getDeviceType() {
        return deviceType_;
      }
      public Builder setDeviceType(YouMai.Basic.YouMaiBasic.Device_Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        deviceType_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeviceType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        deviceType_ = YouMai.Basic.YouMaiBasic.Device_Type.DeviceType_IPhone;
        onChanged();
        return this;
      }
      
      // optional string session_id = 6;
      private java.lang.Object sessionId_ = "";
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSessionId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        sessionId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      void setSessionId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        sessionId_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:YouMai.User.User_Login)
    }
    
    static {
      defaultInstance = new User_Login(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:YouMai.User.User_Login)
  }
  
  public interface Multi_Device_Kicked_NotifyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 timestamp = 1;
    boolean hasTimestamp();
    int getTimestamp();
    
    // optional .YouMai.Basic.Device_Type new_device = 2;
    boolean hasNewDevice();
    YouMai.Basic.YouMaiBasic.Device_Type getNewDevice();
  }
  public static final class Multi_Device_Kicked_Notify extends
      com.google.protobuf.GeneratedMessage
      implements Multi_Device_Kicked_NotifyOrBuilder {
    // Use Multi_Device_Kicked_Notify.newBuilder() to construct.
    private Multi_Device_Kicked_Notify(Builder builder) {
      super(builder);
    }
    private Multi_Device_Kicked_Notify(boolean noInit) {}
    
    private static final Multi_Device_Kicked_Notify defaultInstance;
    public static Multi_Device_Kicked_Notify getDefaultInstance() {
      return defaultInstance;
    }
    
    public Multi_Device_Kicked_Notify getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YouMai.User.YouMaiUser.internal_static_YouMai_User_Multi_Device_Kicked_Notify_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YouMai.User.YouMaiUser.internal_static_YouMai_User_Multi_Device_Kicked_Notify_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private int timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getTimestamp() {
      return timestamp_;
    }
    
    // optional .YouMai.Basic.Device_Type new_device = 2;
    public static final int NEW_DEVICE_FIELD_NUMBER = 2;
    private YouMai.Basic.YouMaiBasic.Device_Type newDevice_;
    public boolean hasNewDevice() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public YouMai.Basic.YouMaiBasic.Device_Type getNewDevice() {
      return newDevice_;
    }
    
    private void initFields() {
      timestamp_ = 0;
      newDevice_ = YouMai.Basic.YouMaiBasic.Device_Type.DeviceType_IPhone;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, newDevice_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, newDevice_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements YouMai.User.YouMaiUser.Multi_Device_Kicked_NotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return YouMai.User.YouMaiUser.internal_static_YouMai_User_Multi_Device_Kicked_Notify_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return YouMai.User.YouMaiUser.internal_static_YouMai_User_Multi_Device_Kicked_Notify_fieldAccessorTable;
      }
      
      // Construct using YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        timestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        newDevice_ = YouMai.Basic.YouMaiBasic.Device_Type.DeviceType_IPhone;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify.getDescriptor();
      }
      
      public YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify getDefaultInstanceForType() {
        return YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify.getDefaultInstance();
      }
      
      public YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify build() {
        YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify buildPartial() {
        YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify result = new YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.newDevice_ = newDevice_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify) {
          return mergeFrom((YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify other) {
        if (other == YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasNewDevice()) {
          setNewDevice(other.getNewDevice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              YouMai.Basic.YouMaiBasic.Device_Type value = YouMai.Basic.YouMaiBasic.Device_Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                newDevice_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 timestamp = 1;
      private int timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(int value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0;
        onChanged();
        return this;
      }
      
      // optional .YouMai.Basic.Device_Type new_device = 2;
      private YouMai.Basic.YouMaiBasic.Device_Type newDevice_ = YouMai.Basic.YouMaiBasic.Device_Type.DeviceType_IPhone;
      public boolean hasNewDevice() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public YouMai.Basic.YouMaiBasic.Device_Type getNewDevice() {
        return newDevice_;
      }
      public Builder setNewDevice(YouMai.Basic.YouMaiBasic.Device_Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        newDevice_ = value;
        onChanged();
        return this;
      }
      public Builder clearNewDevice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        newDevice_ = YouMai.Basic.YouMaiBasic.Device_Type.DeviceType_IPhone;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:YouMai.User.Multi_Device_Kicked_Notify)
    }
    
    static {
      defaultInstance = new Multi_Device_Kicked_Notify(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:YouMai.User.Multi_Device_Kicked_Notify)
  }
  
  public interface User_LogOffOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 user_id = 1;
    boolean hasUserId();
    int getUserId();
    
    // optional string device_id = 2;
    boolean hasDeviceId();
    String getDeviceId();
  }
  public static final class User_LogOff extends
      com.google.protobuf.GeneratedMessage
      implements User_LogOffOrBuilder {
    // Use User_LogOff.newBuilder() to construct.
    private User_LogOff(Builder builder) {
      super(builder);
    }
    private User_LogOff(boolean noInit) {}
    
    private static final User_LogOff defaultInstance;
    public static User_LogOff getDefaultInstance() {
      return defaultInstance;
    }
    
    public User_LogOff getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YouMai.User.YouMaiUser.internal_static_YouMai_User_User_LogOff_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YouMai.User.YouMaiUser.internal_static_YouMai_User_User_LogOff_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 user_id = 1;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getUserId() {
      return userId_;
    }
    
    // optional string device_id = 2;
    public static final int DEVICE_ID_FIELD_NUMBER = 2;
    private java.lang.Object deviceId_;
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          deviceId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      userId_ = 0;
      deviceId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDeviceIdBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDeviceIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static YouMai.User.YouMaiUser.User_LogOff parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static YouMai.User.YouMaiUser.User_LogOff parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.User.YouMaiUser.User_LogOff parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static YouMai.User.YouMaiUser.User_LogOff parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.User.YouMaiUser.User_LogOff parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static YouMai.User.YouMaiUser.User_LogOff parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.User.YouMaiUser.User_LogOff parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static YouMai.User.YouMaiUser.User_LogOff parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static YouMai.User.YouMaiUser.User_LogOff parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static YouMai.User.YouMaiUser.User_LogOff parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(YouMai.User.YouMaiUser.User_LogOff prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements YouMai.User.YouMaiUser.User_LogOffOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return YouMai.User.YouMaiUser.internal_static_YouMai_User_User_LogOff_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return YouMai.User.YouMaiUser.internal_static_YouMai_User_User_LogOff_fieldAccessorTable;
      }
      
      // Construct using YouMai.User.YouMaiUser.User_LogOff.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return YouMai.User.YouMaiUser.User_LogOff.getDescriptor();
      }
      
      public YouMai.User.YouMaiUser.User_LogOff getDefaultInstanceForType() {
        return YouMai.User.YouMaiUser.User_LogOff.getDefaultInstance();
      }
      
      public YouMai.User.YouMaiUser.User_LogOff build() {
        YouMai.User.YouMaiUser.User_LogOff result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private YouMai.User.YouMaiUser.User_LogOff buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        YouMai.User.YouMaiUser.User_LogOff result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public YouMai.User.YouMaiUser.User_LogOff buildPartial() {
        YouMai.User.YouMaiUser.User_LogOff result = new YouMai.User.YouMaiUser.User_LogOff(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deviceId_ = deviceId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof YouMai.User.YouMaiUser.User_LogOff) {
          return mergeFrom((YouMai.User.YouMaiUser.User_LogOff)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(YouMai.User.YouMaiUser.User_LogOff other) {
        if (other == YouMai.User.YouMaiUser.User_LogOff.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              deviceId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 user_id = 1;
      private int userId_ ;
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getUserId() {
        return userId_;
      }
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string device_id = 2;
      private java.lang.Object deviceId_ = "";
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDeviceId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceId_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      void setDeviceId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        deviceId_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:YouMai.User.User_LogOff)
    }
    
    static {
      defaultInstance = new User_LogOff(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:YouMai.User.User_LogOff)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_YouMai_User_User_Login_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_YouMai_User_User_Login_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_YouMai_User_Multi_Device_Kicked_Notify_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_YouMai_User_Multi_Device_Kicked_Notify_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_YouMai_User_User_LogOff_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_YouMai_User_User_LogOff_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021YouMai.User.proto\022\013YouMai.User\032\022YouMai" +
      ".Basic.proto\"\220\001\n\nUser_Login\022\017\n\007user_id\030\001" +
      " \001(\005\022\021\n\tdevice_id\030\002 \001(\t\022\r\n\005phone\030\003 \001(\t\022\013" +
      "\n\003pwd\030\004 \001(\t\022.\n\013device_type\030\005 \001(\0162\031.YouMa" +
      "i.Basic.Device_Type\022\022\n\nsession_id\030\006 \001(\t\"" +
      "^\n\032Multi_Device_Kicked_Notify\022\021\n\ttimesta" +
      "mp\030\001 \001(\005\022-\n\nnew_device\030\002 \001(\0162\031.YouMai.Ba" +
      "sic.Device_Type\"1\n\013User_LogOff\022\017\n\007user_i" +
      "d\030\001 \001(\005\022\021\n\tdevice_id\030\002 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_YouMai_User_User_Login_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_YouMai_User_User_Login_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_YouMai_User_User_Login_descriptor,
              new java.lang.String[] { "UserId", "DeviceId", "Phone", "Pwd", "DeviceType", "SessionId", },
              YouMai.User.YouMaiUser.User_Login.class,
              YouMai.User.YouMaiUser.User_Login.Builder.class);
          internal_static_YouMai_User_Multi_Device_Kicked_Notify_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_YouMai_User_Multi_Device_Kicked_Notify_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_YouMai_User_Multi_Device_Kicked_Notify_descriptor,
              new java.lang.String[] { "Timestamp", "NewDevice", },
              YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify.class,
              YouMai.User.YouMaiUser.Multi_Device_Kicked_Notify.Builder.class);
          internal_static_YouMai_User_User_LogOff_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_YouMai_User_User_LogOff_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_YouMai_User_User_LogOff_descriptor,
              new java.lang.String[] { "UserId", "DeviceId", },
              YouMai.User.YouMaiUser.User_LogOff.class,
              YouMai.User.YouMaiUser.User_LogOff.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          YouMai.Basic.YouMaiBasic.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
