// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YouMai.Basic.proto

package YouMai.Basic;

import com.google.protobuf.InvalidProtocolBufferException;

public final class YouMaiBasic {
  private YouMaiBasic() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum COMMANDID
      implements com.google.protobuf.ProtocolMessageEnum {
    HEART_BEAT(0, 1),
    HEART_BEAT_ACK(1, 2),
    ROUTE_REQ(2, 20),
    USER_LOGIN(3, 101),
    MULTI_DEVICE_KICKED_NOTIFY(4, 102),
    BONDERY_MQ(5, 10000),
    ;
    
    public static final int HEART_BEAT_VALUE = 1;
    public static final int HEART_BEAT_ACK_VALUE = 2;
    public static final int ROUTE_REQ_VALUE = 20;
    public static final int USER_LOGIN_VALUE = 101;
    public static final int MULTI_DEVICE_KICKED_NOTIFY_VALUE = 102;
    public static final int BONDERY_MQ_VALUE = 10000;
    
    
    public final int getNumber() { return value; }
    
    public static COMMANDID valueOf(int value) {
      switch (value) {
        case 1: return HEART_BEAT;
        case 2: return HEART_BEAT_ACK;
        case 20: return ROUTE_REQ;
        case 101: return USER_LOGIN;
        case 102: return MULTI_DEVICE_KICKED_NOTIFY;
        case 10000: return BONDERY_MQ;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<COMMANDID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<COMMANDID>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<COMMANDID>() {
            public COMMANDID findValueByNumber(int number) {
              return COMMANDID.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return YouMai.Basic.YouMaiBasic.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final COMMANDID[] VALUES = {
      HEART_BEAT, HEART_BEAT_ACK, ROUTE_REQ, USER_LOGIN, MULTI_DEVICE_KICKED_NOTIFY, BONDERY_MQ, 
    };
    
    public static COMMANDID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private COMMANDID(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:YouMai.Basic.COMMANDID)
  }
  
  public enum Device_Type
      implements com.google.protobuf.ProtocolMessageEnum {
    DeviceType_IPhone(0, 1),
    DeviceType_Android(1, 2),
    DeviceType_IPad(2, 3),
    DeviceType_AndroidPad(3, 4),
    ;
    
    public static final int DeviceType_IPhone_VALUE = 1;
    public static final int DeviceType_Android_VALUE = 2;
    public static final int DeviceType_IPad_VALUE = 3;
    public static final int DeviceType_AndroidPad_VALUE = 4;
    
    
    public final int getNumber() { return value; }
    
    public static Device_Type valueOf(int value) {
      switch (value) {
        case 1: return DeviceType_IPhone;
        case 2: return DeviceType_Android;
        case 3: return DeviceType_IPad;
        case 4: return DeviceType_AndroidPad;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Device_Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Device_Type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Device_Type>() {
            public Device_Type findValueByNumber(int number) {
              return Device_Type.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return YouMai.Basic.YouMaiBasic.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final Device_Type[] VALUES = {
      DeviceType_IPhone, DeviceType_Android, DeviceType_IPad, DeviceType_AndroidPad, 
    };
    
    public static Device_Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private Device_Type(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:YouMai.Basic.Device_Type)
  }
  
  public interface Heart_BeatOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 user_id = 1;
    boolean hasUserId();
    int getUserId();
  }
  public static final class Heart_Beat extends
      com.google.protobuf.GeneratedMessage
      implements Heart_BeatOrBuilder {
    // Use Heart_Beat.newBuilder() to construct.
    private Heart_Beat(Builder builder) {
      super(builder);
    }
    private Heart_Beat(boolean noInit) {}
    
    private static final Heart_Beat defaultInstance;
    public static Heart_Beat getDefaultInstance() {
      return defaultInstance;
    }
    
    public Heart_Beat getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YouMai.Basic.YouMaiBasic.internal_static_YouMai_Basic_Heart_Beat_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YouMai.Basic.YouMaiBasic.internal_static_YouMai_Basic_Heart_Beat_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 user_id = 1;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getUserId() {
      return userId_;
    }
    
    private void initFields() {
      userId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static YouMai.Basic.YouMaiBasic.Heart_Beat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(YouMai.Basic.YouMaiBasic.Heart_Beat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements YouMai.Basic.YouMaiBasic.Heart_BeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return YouMai.Basic.YouMaiBasic.internal_static_YouMai_Basic_Heart_Beat_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return YouMai.Basic.YouMaiBasic.internal_static_YouMai_Basic_Heart_Beat_fieldAccessorTable;
      }
      
      // Construct using YouMai.Basic.YouMaiBasic.Heart_Beat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return YouMai.Basic.YouMaiBasic.Heart_Beat.getDescriptor();
      }
      
      public YouMai.Basic.YouMaiBasic.Heart_Beat getDefaultInstanceForType() {
        return YouMai.Basic.YouMaiBasic.Heart_Beat.getDefaultInstance();
      }
      
      public YouMai.Basic.YouMaiBasic.Heart_Beat build() {
        YouMai.Basic.YouMaiBasic.Heart_Beat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private YouMai.Basic.YouMaiBasic.Heart_Beat buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        YouMai.Basic.YouMaiBasic.Heart_Beat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public YouMai.Basic.YouMaiBasic.Heart_Beat buildPartial() {
        YouMai.Basic.YouMaiBasic.Heart_Beat result = new YouMai.Basic.YouMaiBasic.Heart_Beat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof YouMai.Basic.YouMaiBasic.Heart_Beat) {
          return mergeFrom((YouMai.Basic.YouMaiBasic.Heart_Beat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(YouMai.Basic.YouMaiBasic.Heart_Beat other) {
        if (other == YouMai.Basic.YouMaiBasic.Heart_Beat.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 user_id = 1;
      private int userId_ ;
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getUserId() {
        return userId_;
      }
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:YouMai.Basic.Heart_Beat)
    }
    
    static {
      defaultInstance = new Heart_Beat(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:YouMai.Basic.Heart_Beat)
  }
  
  public interface Heart_Beat_AckOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 user_id = 1;
    boolean hasUserId();
    int getUserId();
  }
  public static final class Heart_Beat_Ack extends
      com.google.protobuf.GeneratedMessage
      implements Heart_Beat_AckOrBuilder {
    // Use Heart_Beat_Ack.newBuilder() to construct.
    private Heart_Beat_Ack(Builder builder) {
      super(builder);
    }
    private Heart_Beat_Ack(boolean noInit) {}
    
    private static final Heart_Beat_Ack defaultInstance;
    public static Heart_Beat_Ack getDefaultInstance() {
      return defaultInstance;
    }
    
    public Heart_Beat_Ack getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YouMai.Basic.YouMaiBasic.internal_static_YouMai_Basic_Heart_Beat_Ack_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YouMai.Basic.YouMaiBasic.internal_static_YouMai_Basic_Heart_Beat_Ack_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 user_id = 1;
    public static final int USER_ID_FIELD_NUMBER = 1;
    private int userId_;
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getUserId() {
      return userId_;
    }
    
    private void initFields() {
      userId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static YouMai.Basic.YouMaiBasic.Heart_Beat_Ack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat_Ack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat_Ack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat_Ack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat_Ack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat_Ack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat_Ack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat_Ack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat_Ack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static YouMai.Basic.YouMaiBasic.Heart_Beat_Ack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(YouMai.Basic.YouMaiBasic.Heart_Beat_Ack prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements YouMai.Basic.YouMaiBasic.Heart_Beat_AckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return YouMai.Basic.YouMaiBasic.internal_static_YouMai_Basic_Heart_Beat_Ack_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return YouMai.Basic.YouMaiBasic.internal_static_YouMai_Basic_Heart_Beat_Ack_fieldAccessorTable;
      }
      
      // Construct using YouMai.Basic.YouMaiBasic.Heart_Beat_Ack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return YouMai.Basic.YouMaiBasic.Heart_Beat_Ack.getDescriptor();
      }
      
      public YouMai.Basic.YouMaiBasic.Heart_Beat_Ack getDefaultInstanceForType() {
        return YouMai.Basic.YouMaiBasic.Heart_Beat_Ack.getDefaultInstance();
      }
      
      public YouMai.Basic.YouMaiBasic.Heart_Beat_Ack build() {
        YouMai.Basic.YouMaiBasic.Heart_Beat_Ack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private YouMai.Basic.YouMaiBasic.Heart_Beat_Ack buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        YouMai.Basic.YouMaiBasic.Heart_Beat_Ack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public YouMai.Basic.YouMaiBasic.Heart_Beat_Ack buildPartial() {
        YouMai.Basic.YouMaiBasic.Heart_Beat_Ack result = new YouMai.Basic.YouMaiBasic.Heart_Beat_Ack(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof YouMai.Basic.YouMaiBasic.Heart_Beat_Ack) {
          return mergeFrom((YouMai.Basic.YouMaiBasic.Heart_Beat_Ack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(YouMai.Basic.YouMaiBasic.Heart_Beat_Ack other) {
        if (other == YouMai.Basic.YouMaiBasic.Heart_Beat_Ack.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 user_id = 1;
      private int userId_ ;
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getUserId() {
        return userId_;
      }
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:YouMai.Basic.Heart_Beat_Ack)
    }
    
    static {
      defaultInstance = new Heart_Beat_Ack(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:YouMai.Basic.Heart_Beat_Ack)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_YouMai_Basic_Heart_Beat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_YouMai_Basic_Heart_Beat_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_YouMai_Basic_Heart_Beat_Ack_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_YouMai_Basic_Heart_Beat_Ack_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022YouMai.Basic.proto\022\014YouMai.Basic\"\035\n\nHe" +
      "art_Beat\022\017\n\007user_id\030\001 \001(\005\"!\n\016Heart_Beat_" +
      "Ack\022\017\n\007user_id\030\001 \001(\005*\177\n\tCOMMANDID\022\016\n\nHEA" +
      "RT_BEAT\020\001\022\022\n\016HEART_BEAT_ACK\020\002\022\r\n\tROUTE_R" +
      "EQ\020\024\022\016\n\nUSER_LOGIN\020e\022\036\n\032MULTI_DEVICE_KIC" +
      "KED_NOTIFY\020f\022\017\n\nBONDERY_MQ\020\220N*l\n\013Device_" +
      "Type\022\025\n\021DeviceType_IPhone\020\001\022\026\n\022DeviceTyp" +
      "e_Android\020\002\022\023\n\017DeviceType_IPad\020\003\022\031\n\025Devi" +
      "ceType_AndroidPad\020\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_YouMai_Basic_Heart_Beat_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_YouMai_Basic_Heart_Beat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_YouMai_Basic_Heart_Beat_descriptor,
              new java.lang.String[] { "UserId", },
              YouMai.Basic.YouMaiBasic.Heart_Beat.class,
              YouMai.Basic.YouMaiBasic.Heart_Beat.Builder.class);
          internal_static_YouMai_Basic_Heart_Beat_Ack_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_YouMai_Basic_Heart_Beat_Ack_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_YouMai_Basic_Heart_Beat_Ack_descriptor,
              new java.lang.String[] { "UserId", },
              YouMai.Basic.YouMaiBasic.Heart_Beat_Ack.class,
              YouMai.Basic.YouMaiBasic.Heart_Beat_Ack.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
