// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: YouMai.Chat.proto

package YouMai.Chat;

public final class YouMaiChat {
  private YouMaiChat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface IM_MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 src_user_id = 1;
    boolean hasSrcUserId();
    int getSrcUserId();
    
    // optional string src_phone = 2;
    boolean hasSrcPhone();
    String getSrcPhone();
    
    // optional int32 dst_user_id = 3;
    boolean hasDstUserId();
    int getDstUserId();
    
    // optional string dst_phone = 4;
    boolean hasDstPhone();
    String getDstPhone();
    
    // optional string msg = 5;
    boolean hasMsg();
    String getMsg();
  }
  public static final class IM_Message extends
      com.google.protobuf.GeneratedMessage
      implements IM_MessageOrBuilder {
    // Use IM_Message.newBuilder() to construct.
    private IM_Message(Builder builder) {
      super(builder);
    }
    private IM_Message(boolean noInit) {}
    
    private static final IM_Message defaultInstance;
    public static IM_Message getDefaultInstance() {
      return defaultInstance;
    }
    
    public IM_Message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return YouMai.Chat.YouMaiChat.internal_static_YouMai_Chat_IM_Message_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return YouMai.Chat.YouMaiChat.internal_static_YouMai_Chat_IM_Message_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 src_user_id = 1;
    public static final int SRC_USER_ID_FIELD_NUMBER = 1;
    private int srcUserId_;
    public boolean hasSrcUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getSrcUserId() {
      return srcUserId_;
    }
    
    // optional string src_phone = 2;
    public static final int SRC_PHONE_FIELD_NUMBER = 2;
    private java.lang.Object srcPhone_;
    public boolean hasSrcPhone() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getSrcPhone() {
      java.lang.Object ref = srcPhone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          srcPhone_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSrcPhoneBytes() {
      java.lang.Object ref = srcPhone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        srcPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 dst_user_id = 3;
    public static final int DST_USER_ID_FIELD_NUMBER = 3;
    private int dstUserId_;
    public boolean hasDstUserId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getDstUserId() {
      return dstUserId_;
    }
    
    // optional string dst_phone = 4;
    public static final int DST_PHONE_FIELD_NUMBER = 4;
    private java.lang.Object dstPhone_;
    public boolean hasDstPhone() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getDstPhone() {
      java.lang.Object ref = dstPhone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          dstPhone_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDstPhoneBytes() {
      java.lang.Object ref = dstPhone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        dstPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string msg = 5;
    public static final int MSG_FIELD_NUMBER = 5;
    private java.lang.Object msg_;
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          msg_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      srcUserId_ = 0;
      srcPhone_ = "";
      dstUserId_ = 0;
      dstPhone_ = "";
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, srcUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSrcPhoneBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, dstUserId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDstPhoneBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, srcUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSrcPhoneBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, dstUserId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDstPhoneBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static YouMai.Chat.YouMaiChat.IM_Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static YouMai.Chat.YouMaiChat.IM_Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.Chat.YouMaiChat.IM_Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static YouMai.Chat.YouMaiChat.IM_Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.Chat.YouMaiChat.IM_Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static YouMai.Chat.YouMaiChat.IM_Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static YouMai.Chat.YouMaiChat.IM_Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static YouMai.Chat.YouMaiChat.IM_Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static YouMai.Chat.YouMaiChat.IM_Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static YouMai.Chat.YouMaiChat.IM_Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(YouMai.Chat.YouMaiChat.IM_Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements YouMai.Chat.YouMaiChat.IM_MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return YouMai.Chat.YouMaiChat.internal_static_YouMai_Chat_IM_Message_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return YouMai.Chat.YouMaiChat.internal_static_YouMai_Chat_IM_Message_fieldAccessorTable;
      }
      
      // Construct using YouMai.Chat.YouMaiChat.IM_Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        srcUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        srcPhone_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        dstUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        dstPhone_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return YouMai.Chat.YouMaiChat.IM_Message.getDescriptor();
      }
      
      public YouMai.Chat.YouMaiChat.IM_Message getDefaultInstanceForType() {
        return YouMai.Chat.YouMaiChat.IM_Message.getDefaultInstance();
      }
      
      public YouMai.Chat.YouMaiChat.IM_Message build() {
        YouMai.Chat.YouMaiChat.IM_Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private YouMai.Chat.YouMaiChat.IM_Message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        YouMai.Chat.YouMaiChat.IM_Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public YouMai.Chat.YouMaiChat.IM_Message buildPartial() {
        YouMai.Chat.YouMaiChat.IM_Message result = new YouMai.Chat.YouMaiChat.IM_Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.srcUserId_ = srcUserId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.srcPhone_ = srcPhone_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dstUserId_ = dstUserId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dstPhone_ = dstPhone_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof YouMai.Chat.YouMaiChat.IM_Message) {
          return mergeFrom((YouMai.Chat.YouMaiChat.IM_Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(YouMai.Chat.YouMaiChat.IM_Message other) {
        if (other == YouMai.Chat.YouMaiChat.IM_Message.getDefaultInstance()) return this;
        if (other.hasSrcUserId()) {
          setSrcUserId(other.getSrcUserId());
        }
        if (other.hasSrcPhone()) {
          setSrcPhone(other.getSrcPhone());
        }
        if (other.hasDstUserId()) {
          setDstUserId(other.getDstUserId());
        }
        if (other.hasDstPhone()) {
          setDstPhone(other.getDstPhone());
        }
        if (other.hasMsg()) {
          setMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              srcUserId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              srcPhone_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              dstUserId_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              dstPhone_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              msg_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 src_user_id = 1;
      private int srcUserId_ ;
      public boolean hasSrcUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSrcUserId() {
        return srcUserId_;
      }
      public Builder setSrcUserId(int value) {
        bitField0_ |= 0x00000001;
        srcUserId_ = value;
        onChanged();
        return this;
      }
      public Builder clearSrcUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        srcUserId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string src_phone = 2;
      private java.lang.Object srcPhone_ = "";
      public boolean hasSrcPhone() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getSrcPhone() {
        java.lang.Object ref = srcPhone_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          srcPhone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSrcPhone(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        srcPhone_ = value;
        onChanged();
        return this;
      }
      public Builder clearSrcPhone() {
        bitField0_ = (bitField0_ & ~0x00000002);
        srcPhone_ = getDefaultInstance().getSrcPhone();
        onChanged();
        return this;
      }
      void setSrcPhone(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        srcPhone_ = value;
        onChanged();
      }
      
      // optional int32 dst_user_id = 3;
      private int dstUserId_ ;
      public boolean hasDstUserId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getDstUserId() {
        return dstUserId_;
      }
      public Builder setDstUserId(int value) {
        bitField0_ |= 0x00000004;
        dstUserId_ = value;
        onChanged();
        return this;
      }
      public Builder clearDstUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dstUserId_ = 0;
        onChanged();
        return this;
      }
      
      // optional string dst_phone = 4;
      private java.lang.Object dstPhone_ = "";
      public boolean hasDstPhone() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getDstPhone() {
        java.lang.Object ref = dstPhone_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          dstPhone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDstPhone(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dstPhone_ = value;
        onChanged();
        return this;
      }
      public Builder clearDstPhone() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dstPhone_ = getDefaultInstance().getDstPhone();
        onChanged();
        return this;
      }
      void setDstPhone(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        dstPhone_ = value;
        onChanged();
      }
      
      // optional string msg = 5;
      private java.lang.Object msg_ = "";
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMsg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msg_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      void setMsg(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        msg_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:YouMai.Chat.IM_Message)
    }
    
    static {
      defaultInstance = new IM_Message(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:YouMai.Chat.IM_Message)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_YouMai_Chat_IM_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_YouMai_Chat_IM_Message_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021YouMai.Chat.proto\022\013YouMai.Chat\032\022YouMai" +
      ".Basic.proto\"i\n\nIM_Message\022\023\n\013src_user_i" +
      "d\030\001 \001(\005\022\021\n\tsrc_phone\030\002 \001(\t\022\023\n\013dst_user_i" +
      "d\030\003 \001(\005\022\021\n\tdst_phone\030\004 \001(\t\022\013\n\003msg\030\005 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_YouMai_Chat_IM_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_YouMai_Chat_IM_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_YouMai_Chat_IM_Message_descriptor,
              new java.lang.String[] { "SrcUserId", "SrcPhone", "DstUserId", "DstPhone", "Msg", },
              YouMai.Chat.YouMaiChat.IM_Message.class,
              YouMai.Chat.YouMaiChat.IM_Message.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          YouMai.Basic.YouMaiBasic.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
